package entidades;
// Generated 13/10/2020 11:46:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private BigDecimal idCliente;
     private String nombre;
     private String apellido;
     private BigDecimal telefono;
     private String ciudad;
     private String direccion;
     private String nombreUsuario;
     private String contrasena;
     private String correo;
     private Character tipoUsuario;

    public Cliente() {
    }

	
    public Cliente(BigDecimal idCliente) {
        this.idCliente = idCliente;
    }
    public Cliente(BigDecimal idCliente, String nombre, String apellido, BigDecimal telefono, String ciudad, String direccion, String nombreUsuario, String contrasena, String correo, Character tipoUsuario) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.ciudad = ciudad;
       this.direccion = direccion;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.correo = correo;
       this.tipoUsuario = tipoUsuario;
    }
   
    public BigDecimal getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(BigDecimal idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public BigDecimal getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(BigDecimal telefono) {
        this.telefono = telefono;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Character getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(Character tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }




}


