package entidades;
// Generated 13/10/2020 11:46:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private BigDecimal idProduct;
     private String nomber;
     private String descripcion;
     private String codigoUnico;
     private BigDecimal precio;
     private String modelo;
     private String url;
     private String marca;
     private BigDecimal cantidad;

    public Product() {
    }

	
    public Product(BigDecimal idProduct) {
        this.idProduct = idProduct;
    }
    public Product(BigDecimal idProduct, String nomber, String descripcion, String codigoUnico, BigDecimal precio, String modelo, String url, String marca, BigDecimal cantidad) {
       this.idProduct = idProduct;
       this.nomber = nomber;
       this.descripcion = descripcion;
       this.codigoUnico = codigoUnico;
       this.precio = precio;
       this.modelo = modelo;
       this.url = url;
       this.marca = marca;
       this.cantidad = cantidad;
    }
   
    public BigDecimal getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(BigDecimal idProduct) {
        this.idProduct = idProduct;
    }
    public String getNomber() {
        return this.nomber;
    }
    
    public void setNomber(String nomber) {
        this.nomber = nomber;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCodigoUnico() {
        return this.codigoUnico;
    }
    
    public void setCodigoUnico(String codigoUnico) {
        this.codigoUnico = codigoUnico;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


